### ISSUE TITLE
[Market] reference your neuron to the kalliope web site.

### ISSUE THREAD

**Issue by LaMonF** [corus87/kalliope_neuron_kodi#1]
Great Job !
If you want more visibility on your neuron you can reference it on the kalliope web site : https://kalliope-project.github.io/neurons_marketplace.html

You can do it yourself by pushing reference to the kalliope github page project :  https://github.com/kalliope-project/kalliope-project.github.io

:)

**Comment by corus87** [comment]
Thanks for feedback! 
Sry for the long response but Im not sure why I did not got an email notification... 
I tried once to push but failed with the installation of jekyll serve etc.... But if I see it right, I only need to fork the web site, edit _data/community_neurons.yml, put the logo in the image folder and make a PR? 

I would like to push some more neurons in the next days, maybe you can have a quick look into my repository's?

**Comment by Sispheor** [comment]
I confirm, you only need to update the list in the yaml file. Add a logo and reference your repo.
You can also add youtube demo video with a brain example if you want.

**Comment by corus87** [comment]
Okay thanks I will make a PR in the next days, first I want to update the kodi neuron, make some changes and give Kalliope the ability to search and start a movie by voice commands.

**Comment by corus87** [comment]
I have create a new repository for the Kodi neuron, and made a PR.
https://github.com/corus87/kodi-neuron
