### ISSUE TITLE
Missing several options for setting volume, context menu ...

### ISSUE THREAD

**Issue by 1account** [corus87/kalliope_neuron_kodi#2]
Can you add 
- kodi.Application.SetVolume with parameters 0, 10, 20, ..., 100
- kodi.Application.SetMute with paramaters true, false
- kodi.Input.ContextMenu
- kodi.Input.ShowOSD

**Comment by corus87** [comment]
I have create a new repository for the Kodi neuron. 
https://github.com/corus87/kodi-neuron
Check out the changes.
Thanks for the feedback

**Comment by 1account** [comment]
Great, i will definitely try this neuron. You can close the issue if you wish.
